# Generated by Django 5.0.7 on 2024-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_remove_comment_is_provide'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=True),
        ),
    ]
