# Generated by Django 5.0.7 on 2024-08-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_alter_comment_is_provide_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=True),
        ),
    ]
